version: "3"

services:
    nginx:
        container_name: ldv_nginx
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8876:80"
        depends_on:
            - app

    app:
        container_name: ldv_app
        build:
            context: .
            dockerfile: ./_docker/app/Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/var/www/
        depends_on:
            - db

    db:
        container_name: ldv_db
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        volumes:
            - database:/var/lib/postgres

volumes:
    database:
